services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: "true" 
    container_name: twitter_fullstack_web
    depends_on:
      - mariadb
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: twitter_fullstack_db
      DB_USERNAME: root
      DB_PASSWORD: password
      APP_ENV: local
      APP_DEBUG: "true"
    working_dir: /var/www/html

  mariadb:
    image: mariadb:10.6.20
    container_name: twitter_fullstack_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: twitter_fullstack_db
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: twitter_fullstack_phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"

volumes:
  mariadb_data:
